### ISSUE TITLE
Inconsisdent alpha channels

### ISSUE THREAD

**Issue by lehitoskin** [takikawa/racket-rsvg#5]
Loading an SVG gives inconsistent alpha channels. `svg-port->pict` and `svg-file->pict` do not give the image an alpha channel, while `load-svg-bitmap` and `load-svg-from-file` do give the image an alpha channel.

Running `(bitmap (load-svg-bitmap img-path))` will give a pict that has an alpha channel. I think for the sake of consistency, `svg-port->pict` and `svg-file->pict` should return with alpha channels, unless the user specifies otherwise or something.

**Comment by LiberalArtist** [comment]
I would also find an alpha channel desirable in `svg-file->pict` (but thanks for the workaround).

**Comment by samth** [comment]
This bit me today, glad the workaround was available.
